[project]
name = "tcc-context-importance-in-llm-development-tasks"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "pandas>=2.0",
    "matplotlib>=3.7",
    "seaborn>=0.13",
    "numpy>=1.26",
    "pandasai>=2.0",
    "google-genai>=1.0",
    "python-dotenv>=1.0",
]